---
# Playbook filtert hostname, os-release und kernel-version aus den facts
# zur Weiterverarbeitung durch tabCreate.sh
# Christian Linden, 230223
#
- name: get report
#
  hosts: YourServer or Hostgroup from /etc/ansible/hosts
  gather_facts: True
#
  tasks:

    - name: get nodename, distribution version and kernel
      debug:
        msg:
          - "{{ ansible_facts['nodename'] }}"
          - '{{ ansible_distribution }} {{ ansible_distribution_version }}'
          - '{{ ansible_kernel }}'
...
